### PR TITLE
Update README.md to add clarification on building for a 32 bit platform

### PR DESCRIPTION
**Pull request by TechdudeGames**
Add clarification to the README about building for a 32 bit Android platform.

### CODE REVIEW

**Comment by TechdudeGames** [comment]
Since I figured out what caused crash on 32bit builds I thought I might as well help clarify the README.

**Comment by TechdudeGames** [comment]
I am closing this since on the master branch TARGET_BITS=32 does not work with the master branch of the native port, so these instructions are not good.

**Comment by TechdudeGames** [comment]
I made a pull request on the native port side that allows TARGET_BITS to be set on the master branch so that the information I added in the README now is relevant.

**Comment by VDavid003** [comment]
I know I'm kind of late here, but the new commits fixed the issue altogether, which means you can do your host build as 64 bits and it should work on 32 bits too!

**Pull request closed without merging**
